# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: xal
    ports:
      - 5432:5432
    networks:
      - postgres
  centos:
    image: centos
    volumes:
      - appData:/home/data
    tty: true
    networks:
      - postgres
  app:
    image: xal-app
    ports:
      - "8081:8080"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
    name: postgres
volumes:
  appData:
