# Use postgres/example user/password credentials
version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: xal
    ports:
      - 5432:5432
    networks:
      - postgres
  centos:
    image: centos
    container_name: fileServer
    volumes:
      - appData:/home/data
    tty: true
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
    name: postgres
volumes:
  appData:
    external: true
